name: Lint OpenAPI with Spectral

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    name: "Linting (Spectral: spectral:oas)"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Spectral
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'openapi.yml'
